# Generated by Django 4.2 on 2023-09-10 06:35

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('body', ckeditor.fields.RichTextField(verbose_name='بدنه')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('status', models.CharField(choices=[('pub', 'عمومی'), ('drf', 'پیش نویس')], max_length=3, verbose_name='حالت انتشار')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پست',
            },
        ),
    ]
