# Generated by Django 4.2 on 2023-09-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('view_draft_post', 'دیدن پست های پیش نویس'),), 'verbose_name': 'پست'},
        ),
    ]
