# Generated by Django 4.2 on 2023-09-13 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_view_draft_post', 'دیدن پست های پیش نویس'),), 'verbose_name': 'پست'},
        ),
    ]
