# Generated by Django 4.2 on 2023-09-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='confirmed',
            field=models.CharField(choices=[('y', 'بله'), ('n', 'خیر')], default=0, max_length=1, verbose_name='تایید شده'),
            preserve_default=False,
        ),
    ]
