# Generated by Django 4.2 on 2023-09-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_alter_comment_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='confirmed',
            new_name='accepted',
        ),
    ]
