# Generated by Django 4.2 on 2023-09-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_rename_confirmed_comment_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='checked',
            field=models.CharField(choices=[('y', 'بله'), ('n', 'خیر')], default='n', max_length=1, verbose_name='بررسی شده'),
        ),
    ]
