# Generated by Django 4.2 on 2023-09-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='checked',
            field=models.BooleanField(choices=[('y', 'بله'), ('n', 'خیر')], default=False, max_length=1, verbose_name='بررسی شده'),
        ),
    ]
