# Generated by Django 4.2 on 2023-09-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_alter_comment_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='accepted',
            field=models.BooleanField(default=False, max_length=1, verbose_name='تایید شده'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='checked',
            field=models.BooleanField(default=False, max_length=1, verbose_name='بررسی شده'),
        ),
    ]
